let data = {
    animal : [
        '<i class="fas fa-cat"></i>',
        '<i class="fas fa-crow"></i>',
        '<i class="fas fa-dog"></i>',
        '<i class="fas fa-dove"></i>',
        '<i class="fas fa-dragon"></i>',
        '<i class="fas fa-fish"></i>',
        '<i class="fas fa-frog"></i>',
        '<i class="fas fa-hippo"></i>',
        '<i class="fas fa-horse"></i>',
        '<i class="fas fa-horse-head"></i>',
        '<i class="fas fa-kiwi-bird"></i>',
        '<i class="fas fa-otter"></i>',
        '<i class="fas fa-spider"></i>'
    ],
    object : [
        '<i class="fab fa-youtube"></i>',
        '<i class="fas fa-tv"></i>',
        '<i class="fas fa-microphone-alt"></i>',
        '<i class="fas fa-play"></i>',
        '<i class="far fa-hand-point-down"></i>',
        '<i class="fas fa-oil-can"></i>',
        '<i class="fas fa-motorcycle"></i>',
        '<i class="fas fa-car-side"></i>',
        '<i class="fas fa-car"></i>',
        '<i class="fas fa-bus-alt"></i>',
        '<i class="fas fa-bus"></i>',
        '<i class="fas fa-ambulance"></i>',
        '<i class="fas fa-truck-pickup"></i>',
        '<i class="fas fa-truck-monster"></i>',
        '<i class="fas fa-truck"></i>',
        '<i class="fas fa-trailer"></i>',
        '<i class="fas fa-taxi"></i>',
        '<i class="fas fa-shuttle-van"></i>',
        '<i class="fas fa-apple-alt"></i>',
        '<i class="fas fa-drumstick-bite"></i>',
        '<i class="fas fa-football-ball"></i>',
        '<i class="fas fa-tree"></i>',
        '<i class="fas fa-tractor"></i>',
        '<i class="fas fa-mountain"></i>',
        '<i class="fas fa-glass-martini"></i>',
        '<i class="fas fa-beer"></i>',
        '<i class="fas fa-coffee"></i>',
        '<i class="fas fa-flask"></i>',
        '<i class="fas fa-wine-glass-alt"></i>',
        '<i class="fas fa-clinic-medical"></i>',
        '<i class="fas fa-birthday-cake"></i>',
        '<i class="fas fa-calculator"></i>',
        '<i class="fas fa-cut"></i>'
    ],
    letter : 'ABCDEFGHIKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
    number : [
        '0',
        '1',
        '2',
        '3',
        '4',
        '5',
        '6',
        '7',
        '8',
        '9'
    ],
    colors : [
        '#f4dbb0',
        '#ff1515',
        '#035c87',
        '#e1eeff',
        '#272951',
        '#1f7150',
        '#484e75',
        '#5e4474',
        '#c5e6a6',
        '#3bbf45',
        '#e5d5c1',
        '#231a4f',
        '#ecefe9',
        '#322671',
        '#0a0a15',
        '#e3c7cb',
        '#6015a1',
        '#3d4c70',
        '#ffaacc'
    ]
}